modLoader="javafml"
loaderVersion="[4,)"
license="AGPL-3.0"

[[mods]]
modId="zoltraak_cinematic"
version="1.0.0"
displayName="Zoltraak: Cinematic Edition"
authors="Aling7788565"
description='''Frieren-inspired Zoltraak (一般攻撃魔法 - ゾルトラーク) Ultra Realistic & Cinematic Edition. Powered by Photon VFX Engine with true HDR Bloom, Soft Depth Fade, and 1:1 Unity VFX precision.'''

[[dependencies.zoltraak_cinematic]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.zoltraak_cinematic]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.zoltraak_cinematic]]
modId="irons_spellbooks"
type="required"
versionRange="[1.21.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.zoltraak_cinematic]]
modId="photon"
type="optional"
versionRange="[2.2,)"
ordering="AFTER"
side="BOTH"
