modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="frierenvoid"
version="1.11.7"
displayName="Frieren Spells - Iron's Spells Addon"
authors="HanHoYoung"
description='''Frieren-inspired Zoltraak, defensive magic, and a cinematic black hole. An unofficial fan-made Iron's Spells addon.'''
[[dependencies.frierenvoid]]
modId="neoforge"
type="required"
versionRange="[21.1.248,)"
ordering="NONE"
side="BOTH"
[[dependencies.frierenvoid]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.frierenvoid]]
modId="irons_spellbooks"
type="required"
versionRange="[1.21.1-3.16.3,1.21.1-3.17)"
ordering="AFTER"
side="BOTH"
[[dependencies.frierenvoid]]
modId="playeranimator"
type="required"
versionRange="[2,)"
ordering="AFTER"
side="CLIENT"

[[mixins]]
config="frierenvoid.mixins.json"
